package com.Entity;

import java.util.Date;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String spelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.short_spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String shortSpelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.state_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Integer stateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.state_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String stateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.is_hot
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Short isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_city.geo_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String geoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.id
     *
     * @return the value of base_city.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.id
     *
     * @param id the value for base_city.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.code
     *
     * @return the value of base_city.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.code
     *
     * @param code the value for base_city.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.name
     *
     * @return the value of base_city.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.name
     *
     * @param name the value for base_city.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.spelling
     *
     * @return the value of base_city.spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getSpelling() {
        return spelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.spelling
     *
     * @param spelling the value for base_city.spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setSpelling(String spelling) {
        this.spelling = spelling == null ? null : spelling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.short_spelling
     *
     * @return the value of base_city.short_spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getShortSpelling() {
        return shortSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.short_spelling
     *
     * @param shortSpelling the value for base_city.short_spelling
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setShortSpelling(String shortSpelling) {
        this.shortSpelling = shortSpelling == null ? null : shortSpelling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.name_en
     *
     * @return the value of base_city.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.name_en
     *
     * @param nameEn the value for base_city.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.state_id
     *
     * @return the value of base_city.state_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Integer getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.state_id
     *
     * @param stateId the value for base_city.state_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.state_code
     *
     * @return the value of base_city.state_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.state_code
     *
     * @param stateCode the value for base_city.state_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode == null ? null : stateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.country_code
     *
     * @return the value of base_city.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.country_code
     *
     * @param countryCode the value for base_city.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.created_date
     *
     * @return the value of base_city.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.created_date
     *
     * @param createdDate the value for base_city.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.modified_date
     *
     * @return the value of base_city.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.modified_date
     *
     * @param modifiedDate the value for base_city.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.status
     *
     * @return the value of base_city.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.status
     *
     * @param status the value for base_city.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.is_hot
     *
     * @return the value of base_city.is_hot
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Short getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.is_hot
     *
     * @param isHot the value for base_city.is_hot
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setIsHot(Short isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_city.geo_id
     *
     * @return the value of base_city.geo_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getGeoId() {
        return geoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_city.geo_id
     *
     * @param geoId the value for base_city.geo_id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setGeoId(String geoId) {
        this.geoId = geoId == null ? null : geoId.trim();
    }
}