package com.Entity;

import java.util.Date;

public class State {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_state.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.id
     *
     * @return the value of base_state.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.id
     *
     * @param id the value for base_state.id
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.code
     *
     * @return the value of base_state.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.code
     *
     * @param code the value for base_state.code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.country_code
     *
     * @return the value of base_state.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.country_code
     *
     * @param countryCode the value for base_state.country_code
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.name
     *
     * @return the value of base_state.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.name
     *
     * @param name the value for base_state.name
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.name_en
     *
     * @return the value of base_state.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.name_en
     *
     * @param nameEn the value for base_state.name_en
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.created_date
     *
     * @return the value of base_state.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.created_date
     *
     * @param createdDate the value for base_state.created_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.modified_date
     *
     * @return the value of base_state.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.modified_date
     *
     * @param modifiedDate the value for base_state.modified_date
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_state.status
     *
     * @return the value of base_state.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_state.status
     *
     * @param status the value for base_state.status
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}