package com.Dao;

import com.Entity.City;
import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_city
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_city
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_city
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_city
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_city
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int updateByPrimaryKey(City record);
}