package com.Dao;

import com.Entity.Country;
import java.util.List;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_country
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_country
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_country
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_country
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_country
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int updateByPrimaryKey(Country record);
}