package com.Dao;

import com.Entity.State;
import java.util.List;

public interface StateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_state
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_state
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_state
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    State selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_state
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    List<State> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_state
     *
     * @mbg.generated Tue Apr 23 11:36:19 CST 2019
     */
    int updateByPrimaryKey(State record);
}